version: '3.8'
services:
  Datastore:
    image: postgres:16.2
    container_name: datastore
    environment:
      POSTGRES_PASSWORD: "someSuperSecurePwd"
      POSTGRES_DB: "va"
    ports:
      - "5432:5432"
    networks:
      data_network:
        aliases:
          - datastore
  Backend:
    image: backend:latest
    container_name: backend
    environment:
      SPRING_CONFIG_LOCATION: "/backend/application.yml"
    depends_on:
      - Datastore
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: run
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src/main/resources/application.yml:/backend/application.yml
    networks:
      - data_network
  WebFrontend:
    image: webfrontend:latest
    container_name: webfrontend
    build:
      context: ./web-frontend
      dockerfile: Dockerfile
      target: run
    ports:
      - "9090:8080"
    volumes:
      - ./web-frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  data_network:
