
server:
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://datastore:5432/va
    username: postgres
    password: someSuperSecurePwd
  jpa:
    generate-ddl: on
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: mailhog
    port: 1025
    test-connection: true
    username: not_required_for_dev
    password: not_required_for_dev
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  threads:
    virtual:
      enabled: true
